import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { AuthWrapper } from "./auth/pocketbase";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fireship - Next course",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthWrapper>
      <html lang="en">
        <body className={inter.className}>
          <h1 className="border-b border-black">MAIN HEADER</h1>
          <Link href='/notes'><b>Notes</b></Link>
          {children}
        </body>
      </html>
    </AuthWrapper>
  );
}
